schema_version = "1.0.0"

id = "clean_exporter"

version = "1.0.0"

name = "Clean Exporter"

tagline = "Mesh buffer exporter for the Defold game engine"

maintainer = "Agustin R."

type = "add-on"

website = "https://extensions.blender.org/add-ons/clean-exporter/"

tags = ["Import-Export", "Game Engine"]

blender_version_min = "4.2.0"

license = [
  "SPDX:GPL-3.0-or-later",
]

copyright = [
  "2024 Agustin R.",
]

[permissions]
files = "Export .buffer files to disk"
