schema_version = "1.0.0"

id = "clean_game_asset_exporter"

version = "1.0.0"

name = "Clean Game Asset Exporter"

tagline = "Game asset exporter for the Defold game engine"

maintainer = "Agustin R."

type = "add-on"

website = "https://github.com/FlexYourBrain/CleanGameAssetExporter"

tags = ["Game Engine", "Import-Export"]

blender_version_min = "4.2.0"

license = [
  "SPDX:GPL-3.0-or-later",
]

copyright = [
  "2024 Agustin R.",
]

[permissions]
files = "Export game asset files to disk"
